### ISSUE TITLE
Why store two pointers?

### ISSUE THREAD

**Issue by carlsverre** [marvin-j97/byteview#2]
Hello! I randomly encountered this project as it seems we have a shared interest in german style strings and databases. I also recently experimented with what german strings might look like in Rust (https://github.com/carlsverre/german-string) although I didn't go as far as implementing ref counting or almost any other features other than basic layouting.

One thing I can't quite figure out is why you store two pointers. It seems like you could just store one pointer and use an offset to access the other pointer. Seeing as this is already unsafe, I don't think an additional pointer shift would affect the safety of the library.

Appreciate your time! Cheers :)

**Comment by marvin-j97** [comment]
My rationale was that, if I got it right, structs sizes are rounded up to the nearest 8. The basic german string is 16 bytes - with an offset (u32) we get 20 ~> 24. So why waste those 4 bytes. The inlined size can be 20, and for the long string at this point storing a u32 offset or pointer makes no difference for the struct size anymore, so I'd rather use a pointer that can be dereferenced to get the correct slice exactly.

**Comment by carlsverre** [comment]
What do you mean by "with an offset (u32)"? The struct should just be 16 bytes which includes the length (4 bytes) prefix (4 bytes) and pointer/inline data field (8 bytes). Do you mean that you're storing the string along with another offset? What is the additional offset used for?

**Comment by marvin-j97** [comment]
The additional pointer allows slicing up a single byte slice without needing additional heap allocations or memcpy. Similar to what the `bytes` crate does.

In the readme you can see a diagram that shows how multiple slices can share the same heap allocation, yet map to different slices

![](https://github.com/marvin-j97/byteview/blob/main/byteview.png?raw=true)

**Comment by carlsverre** [comment]
Oh nice, that makes a ton of sense. I didn't notice the slice capability when I first scanned through the code. Thank you for clarifying that. Given that new insight, this implementation is really nice.

**Comment by marvin-j97** [comment]
In https://github.com/marvin-j97/byteview/commit/8e4ad3b07f78d96325915467572c47f14f62314d I implemented a feature flag to toggle off the slice capability to make the struct smaller, so it works more like the original German string

**Comment by carlsverre** [comment]
Very cool! Thanks for letting me know!
